### ISSUE TITLE
You got any more them updates

### ISSUE THREAD

**Issue by lerokko** [MaroonAngel/hotbar-switcher#10]
I need my fix.
Under our roof Minecraft does not officially update until this mod does!

**Comment by MaroonAngel** [comment]
😂 Thank you for the reminder! I will get to it ASAP 🙏 
I do appreciate how useful Hotbar Switcher is to you; are there any issues you've had with it that I might be able to fix, or any (smaller) ideas that you'd like to see implemented? 
It's a smaller mod so totally understandable if not. Just wanted to check 😄

**Comment by lerokko** [comment]
I am perfectly happy the way it is. I have grown so dependent on it, its not even funny anymore. (Your mod and voxelmap)
Switching Silk/Fortune, quick swapping to my bed or e-chest. I feel so handicapped without it 😭

If you want to add something maybe a preview of the inventory slot above your selected hotbar slot. But I actually really like the simplicity cause its less likely to break and easier to update (I assume). I also like that it is just one slot at a time. Most mods do 9 slots at once but a lot of anti-cheats kick you for packet spam if you use that (I run my own server(26) so I would know XD)
It is pretty balanced in that regard.

The only issue I could think of is sometimes you get an inventory desync when swapping while you pick up an item into an empty hotbar slot and want to immediately switch it out. But I do not think that is really fixable. That is just minecraft being minecraft ig.

Thank you for time to actually still update this. If you ever have a ko-fi or paypal lmk :)

**Comment by MaroonAngel** [comment]
> maybe a preview of the inventory slot above your selected hotbar slot

I have thought about something like that.... it would definitely be awesome, but I uhh... have had a lot of trouble with minecraft's GUI code in the past 😂 and you are right about it being much easier to update/less prone to breaking. 
I think I have gotten kicked on a server or two before by holding down the swap hotkey while the server was lagging..... lol oops!

Hmm... that desync thing reminds me of the ghost blocks desync bug. I remember using a mod to workaround that by requesting the nearby blocks from the server, so I wonder if I could do something similar with the inventory... I'll have to look into that when I have more time. 

I don't have any ko-fi or paypal link set up but I really appreciate your kind offer! 😄

The [new version for 1.21](https://www.curseforge.com/minecraft/mc-mods/hotbar-switcher/files/5497218) looks like it just got through curseforge approval. Let me know if there are any bugs or anything ^^ happy hotbar switching, lol!
