### ISSUE TITLE
This is my life blood. Please update it to 1.20

### ISSUE THREAD

**Issue by lerokko** [MaroonAngel/hotbar-switcher#7]

**Comment by MaroonAngel** [comment]
I'll update it ASAP :)

**Comment by MaroonAngel** [comment]
Done! Sorry it took so long; I have to wrangle with Fabric and IntelliJ Idea every time a new minecraft version comes out 😂
Should hopefully be approved soon: https://legacy.curseforge.com/minecraft/mc-mods/hotbar-switcher/files/4595612
