### ISSUE TITLE
I am once again asking you to update this mod. (to 1.20.2)

### ISSUE THREAD

**Issue by lerokko** [MaroonAngel/hotbar-switcher#8]
Here to get my fix :D Sorry to bother you with this. Can you update the mod to 1.20.2?
I am using viafabricplus currently to bodge it but a lot of things break.

**Comment by MaroonAngel** [comment]
😂 I loved reading the title of this, thank you for that! I've been swamped lately, but I will try to update as soon as I can :) I'd also look into how possible it is to create a version-agnostic build... we'll see!

And don't worry, you're not bothering me; I appreciate that someone else finds my mod useful hehe!

**Comment by MaroonAngel** [comment]
Okay! I've done some weird modification and removed the version dependency. I didn't actually "update" it, but this build works for me on 1.20.2. It will probably run on future (or past) versions, but may cause a crash if there are any changes to the HUD or... something. 

Could you try this and let me know how it goes? 

https://github.com/MaroonAngel/hotbar-switcher/releases/tag/1.0.7

**Comment by lerokko** [comment]
Works like a charm. Thank you a thousand times. If you push this to Curseforge I will include it in the latest version of my pack.

**Comment by MaroonAngel** [comment]
Finally pushed! Sorry for the wait! Is that your Server26 Clientside pack?

**Comment by lerokko** [comment]
Yes, @MaroonAngel, I make the Server26 Clientside pack. Its a collection of mods I love to play with (or can't play without). I hope its not too much of a bother to ask for updates every now and then.

I assume you found the pack cause its linked as a relation on your mods curseforge page.

**Comment by MaroonAngel** [comment]
Oops, forgot to respond here, my bad! It's not a bother at all :) 

At the time, the Server26 pack was the only related project lol, yep! I haven't actually played much not-heavily-modded minecraft in quite a while, but when I do I will need to try out your modpack 😄
